

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/go-sockaddr"

[[constraint]]
  name = "github.com/hashicorp/raft"
  version = "v1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/raft-boltdb"

[[constraint]]
  branch = "master"
  name = "github.com/justinas/alice"

[[constraint]]
  name = "github.com/ogier/pflag"
  version = "0.0.1"

[[constraint]]
  name = "github.com/uber-go/zap"
  version = "v1.10.0"

[[constraint]]
  name = "github.com/hashicorp/serf"
  version = "v0.8.3"


